### ISSUE TITLE
Hovering values returns wrong expression

### ISSUE THREAD

**Issue by miniwolf** [Microsoft/vscode-debugadapter-node#180] opened 2018-05-11 08:19 UTC
- VSCode Version: 1.23.0
- OS Version: Windows 10

I am not sure whether this belongs as a problem with this repository or it should be moved to either Vscode or OmniSharp as there is a lot of interplay between these things.

When using hovering a value of an array element, while iterating it on a loop. The expression that is returned does not contain the element information, only the ".Priority" part.

As seen in the picture below the value sent in the expression element is ".Priority" instead of the "m_SomeArray[i].Priority".

![hoverissue](https://user-images.githubusercontent.com/710238/39914187-89bfc3dc-5504-11e8-86e6-f9996acea252.png)

**Comment by weinand** [comment] 2018-06-08 08:30
@isidorn please close this as a duplicate of some VS Code issue you probably have.

**Comment by isidorn** [comment] 2018-06-08 08:41
Even though this looks like a dup of https://github.com/Microsoft/vscode/issues/24520 it is not.
The issue here is in word parsing -> created issue https://github.com/Microsoft/vscode/issues/51433
We accept PRs to fix this @miniwolf more deatils in that issue

**Closed by isidorn** 2018-06-08 08:41 UTC
